// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mmr_history.sql

package db

import (
	"context"
	"time"
)

const getMMRHistoryByPuuid = `-- name: GetMMRHistoryByPuuid :many
SELECT id, match_id, puuid, tier, tier_name, ranking_in_tier, mmr_change, elo, date, source, created_at, updated_at FROM mmr_histories
WHERE puuid = ?
ORDER BY date DESC
LIMIT ?
`

type GetMMRHistoryByPuuidParams struct {
	Puuid string `json:"puuid"`
	Limit int64  `json:"limit"`
}

func (q *Queries) GetMMRHistoryByPuuid(ctx context.Context, arg GetMMRHistoryByPuuidParams) ([]MmrHistory, error) {
	rows, err := q.db.QueryContext(ctx, getMMRHistoryByPuuid, arg.Puuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmrHistory{}
	for rows.Next() {
		var i MmrHistory
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Puuid,
			&i.Tier,
			&i.TierName,
			&i.RankingInTier,
			&i.MmrChange,
			&i.Elo,
			&i.Date,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMMRHistory = `-- name: UpsertMMRHistory :exec
INSERT INTO mmr_histories (
    id, match_id, puuid, tier, tier_name, ranking_in_tier,
    mmr_change, elo, date, source, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(match_id, puuid) DO UPDATE SET
    tier = excluded.tier,
    tier_name = excluded.tier_name,
    ranking_in_tier = excluded.ranking_in_tier,
    mmr_change = excluded.mmr_change,
    elo = excluded.elo,
    date = excluded.date,
    source = excluded.source,
    updated_at = excluded.updated_at
`

type UpsertMMRHistoryParams struct {
	ID            string    `json:"id"`
	MatchID       string    `json:"match_id"`
	Puuid         string    `json:"puuid"`
	Tier          int64     `json:"tier"`
	TierName      string    `json:"tier_name"`
	RankingInTier int64     `json:"ranking_in_tier"`
	MmrChange     int64     `json:"mmr_change"`
	Elo           int64     `json:"elo"`
	Date          time.Time `json:"date"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpsertMMRHistory(ctx context.Context, arg UpsertMMRHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMMRHistory,
		arg.ID,
		arg.MatchID,
		arg.Puuid,
		arg.Tier,
		arg.TierName,
		arg.RankingInTier,
		arg.MmrChange,
		arg.Elo,
		arg.Date,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
