// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Match struct {
	MatchID       string    `json:"match_id"`
	MapName       string    `json:"map_name"`
	MapID         string    `json:"map_id"`
	Mode          string    `json:"mode"`
	StartedAt     time.Time `json:"started_at"`
	SeasonID      string    `json:"season_id"`
	TeamRedScore  int64     `json:"team_red_score"`
	TeamBlueScore int64     `json:"team_blue_score"`
	Region        string    `json:"region"`
	Cluster       string    `json:"cluster"`
	Version       string    `json:"version"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type MatchPlayer struct {
	MatchID     string    `json:"match_id"`
	Puuid       string    `json:"puuid"`
	Name        string    `json:"name"`
	Tag         string    `json:"tag"`
	Tier        int64     `json:"tier"`
	TierName    string    `json:"tier_name"`
	Kills       int64     `json:"kills"`
	Deaths      int64     `json:"deaths"`
	Assists     int64     `json:"assists"`
	Score       int64     `json:"score"`
	Team        string    `json:"team"`
	HasWon      bool      `json:"has_won"`
	CharacterID string    `json:"character_id"`
	DamageTaken int64     `json:"damage_taken"`
	DamageDealt int64     `json:"damage_dealt"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MmrHistory struct {
	ID            string    `json:"id"`
	MatchID       string    `json:"match_id"`
	Puuid         string    `json:"puuid"`
	Tier          int64     `json:"tier"`
	TierName      string    `json:"tier_name"`
	RankingInTier int64     `json:"ranking_in_tier"`
	MmrChange     int64     `json:"mmr_change"`
	Elo           int64     `json:"elo"`
	Date          time.Time `json:"date"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Player struct {
	Puuid           string    `json:"puuid"`
	Name            string    `json:"name"`
	Tag             string    `json:"tag"`
	Region          string    `json:"region"`
	AccountLevel    int64     `json:"account_level"`
	Card            string    `json:"card"`
	Title           string    `json:"title"`
	CurrentTier     int64     `json:"current_tier"`
	CurrentTierName string    `json:"current_tier_name"`
	CurrentRr       int64     `json:"current_rr"`
	IsPartialFetch  bool      `json:"is_partial_fetch"`
	LastFetchAt     time.Time `json:"last_fetch_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
